language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-express .
  - docker tag simple-express wano19/simple-express:latest
  - docker build -t simple-reverse-proxy ./image
  - docker tag simple-reverse-proxy wano19/simple-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wano19/simple-express
  - docker push wano19/simple-reverse-proxy

